### ISSUE TITLE
AdapterJS Integration

### ISSUE THREAD

**Issue by coresh** [amw/jpeg_camera#10]
What about AdapterJS integration:

[https://temasys.atlassian.net/wiki/display/TWPP/How+to+integrate+the+Temasys+WebRTC+Plugin+into+your+website](url)

[https://github.com/Temasys/AdapterJS](url)

**Comment by amw** [comment]
How would you like to integrate it?

**Comment by coresh** [comment]
Re: To build on experiences...

> Adapter.js is originally a file that hides the differences between Mozilla Firefox and Google Chrome's implementations of WebRTC

Profit - like:

```
AdapterJS.webRTCReady(function(isUsingPlugin) {
    // The WebRTC API is ready.
    // isUsingPlugin: true if the WebRTC plugin is being used, false otherwise
  
    getUserMedia(constraints, successCb, failCb);
});
```

**Comment by amw** [comment]
I only took a brief look on AdapterJS, but I don't see how it would help us with capturing static images. It's a huge library for supporting P2P video streams that doesn't offer appropriate hooks for capturing an image with its various polyfills. You don't mean to import it just to check if browser is `webRTCReady`, right?

**Comment by coresh** [comment]
Re: 

> You don't mean to import it just to check if browser is webRTCReady, right?


Exactly

**Comment by coresh** [comment]
General reason of adapter.js:
Correct video displaying on my browser screen (chrome Version 50.0.2661.75 Fedora (64-bit)) i have only using adapter.js in other case (jpeg_camera, webcamjs) i have grey ouput into 'video' tag:
[https://webrtc.github.io/samples/src/content/getusermedia/canvas/](url)

**Comment by coresh** [comment]
Also: [https://github.com/otalk/getUserMedia](url)
should be helplful

**Comment by amw** [comment]
JpegCamera already uses `getUserMedia` with a Flash fallback. I've tried the [demo page](https://amw.github.io/jpeg_camera/demo/) on Chrome 50.0.2661.102 (64-bit) OS X and it worked fine without using Flash.

What do you see in your console output?
