### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by evejweinberg** [amw/jpeg_camera#15]
I'm on Chrome, got these errors:

jpeg_camera_with_dependencies.min.js:12 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.(…)navigator.getUserMedia.c._engine_get_image_data @ jpeg_camera_with_dependencies.min.js:12(anonymous function) @ jpeg_camera_with_dependencies.min.js:12
2chrome-extension://cbnaodkpfinfiipjblikofhlhlcickei/sideBarIframe/index.html#/main:1 Mixed Content: The page at 'https://amw.github.io/jpeg_camera/demo/' was loaded over HTTPS, but requested an insecure image 'http://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d'. This content should also be served over HTTPS.
chrome-extension://cbnaodkpfinfiipjblikofhlhlcickei/sideBarIframe/index.html#/main:1 Mixed Content: The page at 'https://amw.github.io/jpeg_camera/demo/' was loaded over HTTPS, but requested an insecure image 'http://www.nature.com/favicon.ico'. This content should also be served over HTTPS.

**Comment by amw** [comment]
The error logs suggest problems with your Chrome extensions. For image capture to work on Chrome the page needs to be hosted from secure origin (https) and all of its resources need to be loaded securely. Some of the things your extensions load are not secure.
