### ISSUE TITLE
Demo not working on Chrome or Firefox

### ISSUE THREAD

**Issue by pcerbino** [amw/jpeg_camera#16]
Demo located on https://amw.github.io/jpeg_camera/demo/ is not working on Chrome and Firefox. The console throws the next error: 

Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.(…)

**Comment by amw** [comment]
Do you know steps to reproduce this issue?

**Comment by sysadmintma** [comment]
Hello ! Thanks a lot for this library !
Using Chrome, Version 56.0.2924.87 on Win10, just loading the page reproduces.
Also on Firefox 49.0.1 on Win10, we have an issue 
"You have denied camera access.
Look for camera icon around your address bar to change your decision."

We are considering using this library in our webiste. Thus we would like to help fixing the issues, would a few man days for our team be helpful ?
aurelien.croq@themoocagency.com

**Comment by amw** [comment]
I have just tested with Chrome 56.0.2924.87 (64-bit) on macOS and it worked fine.

Did you mean that you want to commit some of your developers to investigate and fix the issue? That is always welcome.

If you meant to hire me to help you fix then I'm sorry to say that I can't commit to this at this point in time.
