### ISSUE TITLE
Can't access video Stream 

### ISSUE THREAD

**Issue by tournevis** [amw/jpeg_camera#21]
Hello,

I would like to access video stream to record video. But i can't find any method of JpegCamera class  to access the camera stream. 

See here : https://github.com/amw/jpeg_camera/blob/6171a2915f3fe9eeab8e323e06391529282b2fce/src/jpeg_camera_html5.coffee#L87

**Comment by amw** [comment]
JpegCamera does not support recording videos. It only takes static snapshots.

**Comment by tournevis** [comment]
Ok,
Btw i figured out this by adding a stream parameter to JpegCamera object on line 89
```js
that.stream = stream 
```

**Comment by gabrielstuff** [comment]
@amw would not it be useful to give developers access to the stream?

**Comment by amw** [comment]
I don't know. What are you using it for?

That stream object is only available in the HTML5 engine. It would brake the API when the flash fallback is used.
