### ISSUE TITLE
The demo displays only a disabled camera icon

### ISSUE THREAD

**Issue by Ifedi** [amw/jpeg_camera#25]
In place of the expected image stream, I can only see a disabled camera icon on the demo. The same occurs in Chrome, Opera or Firefox.
Where I was offered the option, I have enabled the webcam camera.
What could be responsible for this?

NB: Here is a screenshot to clarify my point!
![disabled-camera](https://cloud.githubusercontent.com/assets/12812767/24657647/fab3af02-193e-11e7-94a9-d4e6e586470c.png)

**Comment by amw** [comment]
This is actual image sent from your video camera. Either some security software, camera driver or camera itself is generating this.
