### ISSUE TITLE
it is possible to capture video?

### ISSUE THREAD

**Issue by freddi301** [amw/jpeg_camera#27]

**Comment by amw** [comment]
JpegCamera is a JavaScript library that allows you to display a camera stream on a web page and then capture, show and upload JPEG snapshots to the server.

**Comment by freddi301** [comment]
Why so angry :sweat_smile:
Anyway I managed to capture a very short video (3s) whit consecutive camera.capture() and then doing the appropriate conversions in browser.
Very nice work @amw :+1:
