### ISSUE TITLE
A setting for whether the video stream and displayed snapshots are mirrored

### ISSUE THREAD

**Issue by lenton** [amw/jpeg_camera#29]
Our use case of this package is that we are taking pictures of product labels. Obviously, to make it easier to read the text, it would be better for us if the video stream and displayed snapshots were not mirrored.

Currently, there is no way to configure this as it seems to be hardcoded into the package. To me, it would make sense if the existing "mirror" setting was able to control this. According to the documentation, this setting only currently affects whether the uploaded snapshots are mirrored or not.

**Comment by amw** [comment]
Interesting. So who is supposed to read the text? If it's your reviewing staff on the server side then the existing mirror option that controls upload should be enough. Is it the user while they review the image before upload? User can probably read the text better off the product they hold in their hand anyway...

If you don't like the default behavior consider setting this CSS style on the camera's parent element:
https://stackoverflow.com/questions/5406368/can-you-use-css-to-mirror-flip-text#5409373

**Comment by lenton** [comment]
@amw The user who takes the picture of the product needs to ensure that the image is clear, and that the text is readable. Of course, it's much easier to do this if the text isn't mirrored.

Thanks for the work-around, we will consider using this for now. Would be nice to have this feature built in to the package however.

**Comment by JustinStolle** [comment]
I did a quick modification in my fork that respects the mirror option in the UI.
https://github.com/JustinStolle/jpeg_camera
