### ISSUE TITLE
Mirror image

### ISSUE THREAD

**Issue by giorgiobenedetti** [amw/jpeg_camera#33]
Hello, I seen that iamge taken by camera is mirrored. I found "mirror" in camera options, and I added it as     var options = { shutter_ogg_url: "jsCamera/shutter.ogg", shutter_mp3_url: "jsCamera/shutter.mp3", swf_url: "jsCamera/jpeg_camera.swf", mirror: true } but image still wrong (mirrored right-left). How can I solve?

**Comment by giorgiobenedetti** [comment]
File jpeg_camera.js, line 297: JpegCamera._add_prefixed_style(this.video, "transform", "scalex(-1.0)"); change -1.0 to 1.0

File jpeg_camera.js, line 389: JpegCamera._add_prefixed_style(this.displayed_canvas, "transform", "scalex(-1.0)"); change -1.0 to 1.0

File jpeg_camera.js, line 823: JpegCamera._add_prefixed_style(that._extra_canvas, "transform", "scalex(-1.0)"); change -1.0 to 1.0

That display a video not mirrored and save right images.

**Comment by amw** [comment]
Please refer to the documentation to read about the `mirror` option of JpegCamera:
https://amw.github.io/jpeg_camera/doc/class/JpegCamera.html

Or search old issues to see what has been discussed before: #29
