### ISSUE TITLE
a way to use the rear camera or choose cameras? 

### ISSUE THREAD

**Issue by creativereason** [amw/jpeg_camera#36]
For tablets and similar devices that have multiple cameras (front and rear) do you have a way to choose which one is used?

**Comment by creativereason** [comment]
Any feedback on this?

**Comment by seanhak** [comment]
+1 would be nice to have.

I tried to modify get_user_media_options accept facingMode but couldn't get it working. I think this is because its using the legacy method. I had to move on as this feature was nice to have at the moment.

**Comment by amw** [comment]
There's no way to select camera input in this library. I don't even know if spec allows it – maybe the choice is left to the user. I will accept a PR if you find a way to implement it.
