### ISSUE TITLE
Chrome canary (v48.x) - demo fails

### ISSUE THREAD

**Issue by IanYates** [amw/jpeg_camera#4]
Hi,

Nice looking library :)  I came here after seeing the new link to it from webcamjs.  I tried your demo in Chrome Canary v48 and received this message in the developer tools

```
jpeg_camera_with_dependencies.min.js:11 getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```
The helper text on the page about using the camera icon unfortunately doesn't apply - it seems access to `getUserMedia()` is completely blocked if not using HTTPS.

FYI: That goo.gl link redirects to https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

This caught me by surprise.  I'm only raising this to see if you know of a way to detect this circumstance and perhaps allow fallback to Flash since it's not blocked.

**Comment by amw** [comment]
Thanks for reporting this. I understand Google's reasoning and agree with it in general. If you want to capture picture of your user you probably should do so from cryptographically confirmed origin.

The app for which I've developed this library is served over HTTPS connection so I'm going to be fine. I suggest others follow track. I've also updated all the demo links to point to HTTPS version.

Having said that I realize this might be inconvenience for some developers especially while testing dev versions of their websites. I could fall back to Flash in this situation, but right now I don't know of a good way to detect this issue. Canary Chrome reports availability of `getUserMedia` on http connections, it just automatically rejects requests to use it. It looks as if user said "No". I don't want to detect browser version string.

**Comment by IanYates** [comment]
Thanks for the reply.  I too don't have a big deal with the HTTPS requirement but was wondering if a fallback was possible.  It seems like that's not the case at the moment without, as you said, gross things like user-agent sniffing or the like.  I suppose if all browsers go this way then eventually just the page being served over HTTP would be enough of a signal.
My use-case is an app deployed in-house to 60+ different businesses.  I know how to run a little certificate authority alongside a domain controller on the windows networks of my clients, but I'm not their IT team and getting such things isn't always easy, particularly once I mention "group policy" to ensure their in-house certificate authority is trusted by all of their endpoints.  None of this is your problem though :)

I'll explore the library a bit more later today or tomorrow to see if there's a nice way I can force the flash fallback myself.  That way I can have a site switch, if necessary, to disable the use of getUserMedia for sites that can't use HTTPS internally.

**Comment by amw** [comment]
In-house meaning it's not served on the public internet? Then yes, you could use a private Certificate Authority. Or you could still deploy on the internet, get a regular SSL cert and redirect your users with some kind of authentication token. I assume they still have access to the internet even though they're on the company network. Though if you care about image upload bandwidth and latency then intranet is the way to go.

In either case I would suggest you try to make `getUserMedia` work. It's a much better user experience and it has much better performance too. That Flash control panel is simply abysmal. Also, Chrome already knows and controls when Flash accesses user's webcam and they could easily use the same HTTPS restriction for Flash.

If you still want to use Flash, then there's a way to force it with JpegCamera. Simply set this
`window.jpeg_camera_force_flash = true` *before* including JpegCamera JS files. For now you'll have to write your protocol and browser version detection yourself.
