### ISSUE TITLE
Is it possible to crop the image from the camera?

### ISSUE THREAD

**Issue by denisxxx** [amw/jpeg_camera#5]
First of all thank you for a great library! My question is if it is possible to crop image like webcam.js does, i need to capture the face only so there is no need to show what is around.

**Comment by amw** [comment]
Capturing faces is actually my main use of this library, but you can't crop the image freely. You can control the aspect ratio of video by changing the size of the video container. The library will crop the input stream to fit it. The algorithm is to always keep full resolution of one dimension and discard equal parts from the sides of the other.

I do it to set a vertical camera stream similar to FaceTime. I do not detect how big the actual face is, so I'm going to send full height of the input stream.

**Comment by denisxxx** [comment]
thank you, will try that!
