### ISSUE TITLE
No Camera Access in Demo File

### ISSUE THREAD

**Issue by jawadrasheed** [amw/jpeg_camera#9]
If I open the downloaded demo file, it does not access the camera. It displays the placeholder in the canvas.

**Comment by amw** [comment]
I don't think the demo is supposed to work outside a web server. You can't just open the file from disk. Use a local web server for testing.

You can view the demo online at https://amw.github.io/jpeg_camera/demo/ . These are exactly the same files that you download from the repo.

**Comment by jawadrasheed** [comment]
Thanks alot for your quick response. Actually I am new coder, so sorry for asking this type of question.
